### ISSUE TITLE
How to pass installation token for powershell script?

### ISSUE THREAD

**Issue by oliverpickles2019** [CrowdStrike/Cloud-Azure#23]
Hello,

I have attempted to deploy your running powershell script in my terraform vm extension module. I examined the powershell script and could not find any reference to passing installation tokens?

Is this possible? 

It appears that the linux bash scripts have this option but not powershell? 

maybe I am missing something?

**Comment by oliverpickles2019** [comment]
Thanks for the response. Tested this and works :)

Yes please. It would be more ideal to have an option for this directly.

Also for VMSS extensions, is there a way i can elevate this to administrator? Based on the documentation this is a requirement right?

**Comment by redhatrises** [comment]
> Thanks for the response. Tested this and works :)
> 
> Yes please. It would be more ideal to have an option for this directly.
> 
> Also for VMSS extensions, is there a way i can elevate this to administrator? Based on the documentation this is a requirement right?

You do need to be admin to install. For terraform, I would checkout the terraform documentation for how to handle this. Here is an example in ARM at https://github.com/CrowdStrike/Cloud-Azure/blob/main/vm/vmss/windows/template.json#L288 which you might need to add to your terraform provider.
