### ISSUE TITLE
Could not read meta data from /tmp/tmp.DC8beNp6oV/falcon-sensor.deb

### ISSUE THREAD

**Issue by AmudaPalani** [CrowdStrike/Cloud-Azure#26]
When I run the following command I am getting an error:

az vm extension set \
  --resource-group PALANI_DEV2_RG \
  --vm-name testvm2 \
  --name customScript \
  --publisher Microsoft.Azure.Extensions \
  --protected-settings '{"fileUris": ["https://raw.githubusercontent.com/crowdstrike/falcon-scripts/main/bash/install/falcon-linux-install.sh"],"commandToExecute": "export FALCON_CLIENT_ID=123 && export FALCON_CLIENT_SECRET=abc && /bin/bash falcon-linux-install.sh"}'

Output:
(VMExtensionProvisioningError) VM has reported a failure when processing extension 'customScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=100
[stdout]
Falcon Sensor Install  ... 
[stderr]
E: Invalid archive member header
E: Could not read meta data from /tmp/tmp.DC8beNp6oV/falcon-sensor.deb
E: The package lists or status file could not be parsed or opened.
"

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot 
Code: VMExtensionProvisioningError
Message: VM has reported a failure when processing extension 'customScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=100
[stdout]
Falcon Sensor Install  ... 
[stderr]
E: Invalid archive member header
E: Could not read meta data from /tmp/tmp.DC8beNp6oV/falcon-sensor.deb
E: The package lists or status file could not be parsed or opened.
"

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot

**Comment by redhatrises** [comment]
@AmudaPalani can you also provide the OS that were attempting to install?

**Comment by redhatrises** [comment]
Closing as no further information was provided. Please re-open with the necessary informaiton.
