### ISSUE TITLE
vm-extensions bootstrap script does not work

### ISSUE THREAD

**Issue by mccbryan3** [CrowdStrike/Cloud-Azure#6]
vm-extensions bootstrap script does not work and points to a deprecated script in the Cloud-AWS repository

**Comment by redhatrises** [comment]
I believe it just needs to be updated to https://github.com/CrowdStrike/Cloud-AWS/blob/master/Agent-Install-Examples/bash/install.sh

**Comment by mccbryan3** [comment]
right... that one works but it is full of AWS SSM stuffs. I would like to work off of a central install script that is based on this one but generalized and not tie it directly to the AWS repo...  Perhaps this one https://github.com/CrowdStrike/falcon-linux-install-bash with some work done to it for automation.

**Comment by redhatrises** [comment]
> right... that one works but it is full of AWS SSM stuffs. I would like to work off of a central install script that is based on this one but generalized and not tie it directly to the AWS repo... Perhaps this one https://github.com/CrowdStrike/falcon-linux-install-bash with some work done to it for automation.

For sure! The AWS one is linux distro agnostic and is a very good starting point.
